import { encounters,dateScenes,encounterReactionMap } from './content.js';
import { state,candidates,firstFour,currentCandidate,shell,largePortrait,miniPortrait,addMemory,hiddenRecord,navigate,resetLife,requestRender } from './runtime.js';

export function renderIntro(){shell(`<div class="panel intro"><div><div class="kicker">A LIFE RUN</div><h1>这一年，<br>你会遇见一些人。</h1><p>没有正确答案，也没有理想型测试。你只需要像自己一样生活，看看一段关系最后会把人生带到哪里。</p><button class="primary" id="start">开始这一年</button></div></div>`);document.querySelector('#start').onclick=()=>navigate('encounter');}

export function renderEncounter(){const id=firstFour[state.encounterIndex],candidate=candidates[id],e=encounters[id];const response=state.encounterLine==null?`<div class="choices">${e.responses.map((x,i)=>`<button class="choice encounter-line" data-i="${i}">${x}</button>`).join('')}</div>`:`<div class="response-box">你说：${e.responses[state.encounterLine]}</div><div class="counter">这一刻，不用分析。只按第一感觉。</div><div class="reactions"><button class="reaction" data-r="WANT">很想再见</button><button class="reaction" data-r="MAYBE">可以再看看</button><button class="reaction" data-r="NO">没什么感觉</button></div>`;shell(`<div class="panel scene-grid">${largePortrait(candidate)}<div class="story"><div class="kicker">${state.encounterIndex+1} / 4 · ${e.scene}</div><h1>${candidate.presentation.name}</h1><p class="body">${e.intro}</p><div class="dialogue">${e.line}</div>${response}</div></div>`);document.querySelectorAll('.encounter-line').forEach(b=>b.onclick=()=>{state.encounterLine=Number(b.dataset.i);requestRender();});document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const r=encounterReactionMap[b.dataset.r];state.reactions[id]={...r,playerLineIndex:state.encounterLine};if(r.wouldConsider)addMemory(`遇见 ${candidate.presentation.name}`,`${r.label}。${e.responses[state.encounterLine]}`);state.encounterIndex+=1;state.encounterLine=null;navigate(state.encounterIndex>=4?'select':'encounter');});}

const eligible=()=>firstFour.filter(id=>state.reactions[id]?.wouldConsider&&!state.shortlistRejected.has(id));
export function renderSelect(){const ids=eligible();if(!ids.length){shell(`<div class="panel transition"><div class="kicker">这一年</div><h1 class="time">没有勉强开始。</h1><p>四个人都没有让你想继续认识。也许这本来就是一个真实结果。</p><button class="primary" id="again">换一年再来</button></div>`);document.querySelector('#again').onclick=resetLife;return;}shell(`<div class="panel event-card"><div class="kicker">周末到了</div><h1>你最想先见谁？</h1><p class="body">不是选“条件最好”的人。只是这个周末，你最自然地想把时间给谁。</p><div class="people-grid">${ids.map(id=>{const c=candidates[id];return `<button class="person-card" data-id="${id}">${miniPortrait(c)}<h3>${c.presentation.name}</h3><p>${c.presentation.summary}</p></button>`}).join('')}</div></div>`);document.querySelectorAll('.person-card').forEach(b=>b.onclick=()=>{state.selectedCandidateId=b.dataset.id;state.dateIndex=0;state.relationshipState={connection:0,trust:0,autonomy_balance:0,resentment:0,commitment:0,exit_constraint:0};state.events=[];navigate('date');});}

export function renderDate(){const c=currentCandidate(),nodes=dateScenes[c.id];if(state.dateIndex>=nodes.length)return renderDateDecision();const n=nodes[state.dateIndex];shell(`<div class="panel scene-grid">${largePortrait(c)}<div class="story"><div class="kicker">${n.kicker}</div><h1>${n.title}</h1><p class="body">${n.body}</p><div class="dialogue">${n.line}</div><div class="choices">${n.choices.map((x,i)=>`<button class="choice date-choice" data-i="${i}">${x.text}</button>`).join('')}</div></div></div>`);document.querySelectorAll('.date-choice').forEach(b=>b.onclick=()=>{const ch=n.choices[Number(b.dataset.i)];hiddenRecord({eventId:`FIRST_DATE_${state.dateIndex+1}`,action:`CHOICE_${b.dataset.i}`,tags:ch.tags,responseCode:'DATE',memoryTitle:state.dateIndex===0?'第一次约会':null,memoryDetail:state.dateIndex===0?`${c.presentation.name} · ${n.title}`:null});state.dateIndex+=1;requestRender();});}
function renderDateDecision(){const c=currentCandidate();shell(`<div class="panel scene-grid">${largePortrait(c)}<div class="story"><div class="kicker">第二天 · 10:24</div><h1>手机亮了一下。</h1><div class="dialogue">“昨天挺开心的。下周还想见你。”</div><div class="choices"><button class="choice" data-d="YES">“我也想。”</button><button class="choice" data-d="MAYBE">“可以，再认识看看。”</button><button class="choice" data-d="NO">“我觉得还是算了。”</button></div></div></div>`);document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{if(b.dataset.d==='NO'){state.shortlistRejected.add(c.id);state.selectedCandidateId=null;state.events=[];navigate('select');return;}hiddenRecord({eventId:'RELATIONSHIP_START',action:b.dataset.d,tags:b.dataset.d==='YES'?['TOGETHER_POSITIVE']:['RESPONSIVE'],memoryTitle:'你们开始认真见面',memoryDetail:`你决定继续认识 ${c.presentation.name}。`});navigate('threeMonths');});}
export function renderThreeMonths(){shell(`<div class="panel transition"><div class="kicker">时间往前走</div><h1 class="time">三个月后</h1><p>你们已经很熟了。很多事情不再需要特意约，聊天也从“你喜欢什么”变成了“今天几点回来”。</p><button class="primary" id="continue">继续生活</button></div>`);document.querySelector('#continue').onclick=()=>navigate('light');}
