import { resolveWeekend,resolveWorkweek,resolvePlanChange,resolveFriendGathering,resolveExpressSpace,resolveCohabitation } from './logic.js';
import { state,currentCandidate,shell,largePortrait,hiddenRecord,navigate,requestRender } from './runtime.js';

function buildLightEvents(c){return ['WEEKEND','WORKWEEK',c.traits.social_energy>=8?'FRIEND_GATHERING':'PLAN_CHANGE'];}
function lightScene(c,eventId){
  if(eventId==='WEEKEND'){const highSocial=c.traits.social_energy>=8,highAuto=c.traits.autonomy_need>=8,highAvail=c.traits.daily_availability>=8;return{icon:'☀︎',title:'一个普通周末',body:highSocial?'周六中午，他说晚上几个朋友临时约了聚会。':highAuto?'周六早上，他已经安排好了自己的运动和学习。':highAvail?'周六一早，他问你今天想一起去哪。':'这周都挺忙，终于到了周六。',line:highSocial?'“你要是想来就一起，不想来也没关系。”':highAuto?'“下午我有自己的安排，晚上一起吃饭？”':highAvail?'“今天都留给我们，你想怎么过？”':'“今天别排太满，随便走走？”',choices:[{text:'“一起吧。”',action:'JOIN',tolerance:'LIKE',reason:null},{text:'“我们各做各的，晚上见。”',action:'SEPARATE',tolerance:'ACCEPT',reason:null},{text:'“我想先把今天怎么过说清楚。”',action:'NEGOTIATE',tolerance:'CHANGE_REQUIRED',reason:'LOW_TIME'},{text:'“又是这样，我有点受够了。”',action:'PROTEST',tolerance:'CANNOT_CONTINUE',reason:'LOW_PRIORITY'}],resolver:resolveWeekend};}
  if(eventId==='WORKWEEK'){const low=c.traits.daily_availability<=3;return{icon:'◷',title:'一周又过去了',body:low?'这周你们有三天几乎只在睡前说了几句话。':'这周你们都忙，但还能找到一些稳定的时间。',line:low?'“最近确实有点过头。等这阵过去会好一些。”':'“周四晚上我们别安排别的，留给我们？”',choices:[{text:'“这阵忙我能理解。”',action:'ACCEPT',tolerance:'ACCEPT',reason:null},{text:'“至少固定留一个晚上给我们。”',action:'REQUEST_FIXED_TIME',tolerance:'CHANGE_REQUIRED',reason:'LOW_TIME'},{text:'“我需要的不只是偶尔见一面。”',action:'REQUEST_MORE_TIME',tolerance:'CHANGE_REQUIRED',reason:'LOW_TIME'},{text:'“我不想一直等工作有空。”',action:'PROTEST',tolerance:'CANNOT_CONTINUE',reason:'LOW_PRIORITY'}],resolver:resolveWorkweek};}
  if(eventId==='FRIEND_GATHERING')return{icon:'✦',title:'朋友的周末局',body:'周五晚上，他说几个很熟的朋友临时组了局，其中也有你没见过的人。',line:'“我想去。你想一起就一起，不想去也完全可以。”',choices:[{text:'“走，一起去。”',action:'JOIN',tolerance:'LIKE',reason:null},{text:'“你去吧，我今晚想自己待着。”',action:'SKIP',tolerance:'ACCEPT',reason:null},{text:'“可以，不过有些边界我想先说清楚。”',action:'DISCUSS_BOUNDARY',tolerance:'CHANGE_REQUIRED',reason:'SOCIAL_BOUNDARY'},{text:'“我不喜欢你总把社交放这么前面。”',action:'PROTEST',tolerance:'CANNOT_CONTINUE',reason:'LOW_PRIORITY'}],resolver:resolveFriendGathering};
  return{icon:'↻',title:'计划又临时变了',body:'你们本来约好晚上吃饭。下午五点，他发来消息，说事情有变化。',line:'“时间可能要往后挪两个小时。你介意吗？”',choices:[{text:'“没事，晚点见。”',action:'ACCEPT',tolerance:'ACCEPT',reason:null},{text:'“可以，但下次早点告诉我。”',action:'NEGOTIATE',tolerance:'CHANGE_REQUIRED',reason:'UNPREDICTABLE'},{text:'“今晚还是按原来吧，我不想一直跟着变。”',action:'KEEP_ORIGINAL',tolerance:'CHANGE_REQUIRED',reason:'UNPREDICTABLE'},{text:'“我真的很讨厌这种随时会变的生活。”',action:'PROTEST',tolerance:'CANNOT_CONTINUE',reason:'UNPREDICTABLE'}],resolver:resolvePlanChange};
}
function responseCopy(c,r){const name=c.presentation.name;if(['ACCEPT','BOUNDARY_RESPECTED'].includes(r.code))return`${name} 没有马上为自己辩解，而是顺着你的话把接下来的安排重新说了一遍。`;if(r.code==='NEGOTIATE_BOUNDARY')return`${name} 愿意调整，但也把自己不能放弃的部分说得很清楚。你们最后各退了一点。`;if(['PARTIAL','BOUNDARY_PARTIAL'].includes(r.code))return`${name} 听进了一部分，但你能感觉到，这件事并没有真的谈完。`;if(['RESIST','BOUNDARY_RESISTED'].includes(r.code))return`${name} 明显不太认同。他没有吵，但也没有准备改变自己的安排。`;if(r.code==='SPACE_RESPECTED')return`${name} 很自然地接受了你们各自安排。晚上见面时，也没有追问你白天每个小时去了哪里。`;if(r.code==='JOIN')return'你们一起去了。事情本身没多特别，但那天的时间过得很快。';return'事情就这样过去了。它不算大事，却悄悄变成了你们生活的一部分。';}

export function renderLight(){const c=currentCandidate();if(!state.lightEvents.length)state.lightEvents=buildLightEvents(c);if(state.lightIndex>=state.lightEvents.length){navigate('montage');return;}const id=state.lightEvents[state.lightIndex],s=lightScene(c,id);shell(`<div class="panel event-card"><div class="event-icon">${s.icon}</div><div class="kicker">第 ${state.lightIndex+1} 个日常片段</div><h1>${s.title}</h1><p class="body">${s.body}</p><div class="dialogue">${s.line}</div><div class="choices">${s.choices.map((x,i)=>`<button class="choice light-choice" data-i="${i}">${x.text}</button>`).join('')}</div></div>`);document.querySelectorAll('.light-choice').forEach(b=>b.onclick=()=>{const ch=s.choices[Number(b.dataset.i)],r=s.resolver(c,ch.action);hiddenRecord({eventId:id,action:ch.action,tags:r.tags,tolerance:ch.tolerance,reasonCode:ch.reason,responseCode:r.code,memoryTitle:ch.tolerance==='CANNOT_CONTINUE'?`${s.title}让你第一次认真动摇`:null,memoryDetail:ch.text});state.pendingLight={copy:responseCopy(c,r)};navigate('lightResult');});}
export function renderLightResult(){const c=currentCandidate();shell(`<div class="panel event-card"><div class="kicker">事情之后</div><h1>${c.presentation.name} 的反应</h1><div class="response-box">${state.pendingLight.copy}</div><button class="primary" id="next">继续往前</button></div>`);document.querySelector('#next').onclick=()=>{state.lightIndex+=1;navigate('light');};}
function montageText(c){const lines=[];lines.push(c.traits.daily_availability<=3?'你已经习惯工作日不一定能见到他。':c.traits.daily_availability>=8?'你们大多数晚上都会一起吃饭。':'你们有自己的节奏，不算黏，也不会太久不见。');lines.push(c.traits.predictability>=8?'很多安排慢慢变得固定，你大概知道下周会怎么过。':c.traits.predictability<=3?'计划常常临时改变，你开始学会给生活留一点空白。':'有些事情固定，有些事情还是要临时商量。');lines.push(c.traits.autonomy_need>=8?'你们各自都有不少自己的时间。':'你们越来越多事情是一起做的。');return lines.join(' ');}
export function renderMontage(){const c=currentCandidate();shell(`<div class="panel transition"><div class="kicker">时间往前走</div><h1 class="time">半年后</h1><p>${montageText(c)}</p><button class="primary" id="continue">继续</button></div>`);document.querySelector('#continue').onclick=()=>navigate('recurring');}
function recurringScene(c){if(c.id==='P01')return{title:'又一个被工作打断的周末',body:'这是一个月里第三次。你们本来约好晚上吃饭，他下午临时发来消息。',line:'“我知道最近有点过分。今天这个事我得处理。”',choices:[{text:'“忙可以，但我们得有真正属于我们的时间。”',tolerance:'CHANGE_REQUIRED',reason:'LOW_TIME',tags:['RESPONSIVE']},{text:'“最难受的不是你忙，是每次都先决定完再告诉我。”',tolerance:'CHANGE_REQUIRED',reason:'LOW_PRIORITY',tags:['PREDICTABLE']},{text:'“如果以后一直这样，我可能真的不想继续。”',tolerance:'CANNOT_CONTINUE',reason:'LOW_TIME',tags:['DISTANCE']}]};if(c.id==='P02')return{title:'你开始想要一个完全属于自己的周末',body:'最近几乎所有周末都在一起。周宁已经在问下周去哪，但你忽然很想什么都不安排。',line:'“怎么了？我们不是一直都这样吗？”',choices:[{text:'“我爱你，但我也需要一点自己的时间。”',tolerance:'CHANGE_REQUIRED',reason:'TOO_CLOSE',action:'ASK_WEEKLY_SPACE'},{text:'“偶尔分开过周末，对我反而更舒服。”',tolerance:'ACCEPT',reason:null,action:'ASK_ONE_NIGHT'},{text:'“如果所有事都必须一起，我会越来越窒息。”',tolerance:'CANNOT_CONTINUE',reason:'TOO_CLOSE',action:'ASK_SEPARATE_HOBBY'}],space:true};if(c.id==='P03')return{title:'第三次临时改计划',body:'你已经穿好鞋准备出门，许澈发消息说朋友那边突然有事，原来的安排又要变。',line:'“我知道你可能会烦。要不你决定，我们按你的来。”',choices:[{text:'“我不怕变化，但至少早点告诉我。”',tolerance:'CHANGE_REQUIRED',reason:'UNPREDICTABLE',tags:['RESPONSIVE']},{text:'“今天就算了，我自己安排。”',tolerance:'ACCEPT',reason:null,tags:['SPACE_RESPECTED']},{text:'“这种随时改变的日子我真的过不久。”',tolerance:'CANNOT_CONTINUE',reason:'UNPREDICTABLE',tags:['DISTANCE']}]};return{title:'现实开始进入你们的未来',body:'沈知准备转一个新的方向。短期收入不会变好，甚至可能更紧一点。你们刚好也在讨论要不要换一个更舒服的住处。',line:'“我想继续做这件事，但我知道这会影响我们。”',choices:[{text:'“我可以接受一段时间普通一点，只要你是真的在往前走。”',tolerance:'ACCEPT',reason:null,tags:['RESPONSIVE']},{text:'“我支持，但我们得先把钱怎么过说清楚。”',tolerance:'CHANGE_REQUIRED',reason:'FINANCIAL_RISK',tags:['PREDICTABLE']},{text:'“我发现我需要更确定的现实基础。”',tolerance:'CANNOT_CONTINUE',reason:'FINANCIAL_RISK',tags:['DISTANCE']}]};}
export function renderRecurring(){const c=currentCandidate(),s=recurringScene(c);shell(`<div class="panel scene-grid">${largePortrait(c)}<div class="story"><div class="kicker">一年以后 · 第一个反复问题</div><h1>${s.title}</h1><p class="body">${s.body}</p><div class="dialogue">${s.line}</div><div class="choices">${s.choices.map((x,i)=>`<button class="choice recurring-choice" data-i="${i}">${x.text}</button>`).join('')}</div></div></div>`);document.querySelectorAll('.recurring-choice').forEach(b=>b.onclick=()=>{const ch=s.choices[Number(b.dataset.i)];let tags=ch.tags||[],code='PLAYER_POSITION';if(s.space){const r=resolveExpressSpace(c,ch.action);tags=r.tags;code=r.code;}hiddenRecord({eventId:'RECURRING_ISSUE',action:`CHOICE_${b.dataset.i}`,tags,tolerance:ch.tolerance,reasonCode:ch.reason,responseCode:code,memoryTitle:'第一个反复出现的问题',memoryDetail:ch.text});navigate('cohabit');});}
export function renderCohabit(){const c=currentCandidate();shell(`<div class="panel scene-grid">${largePortrait(c)}<div class="story"><div class="kicker">一年半以后 · 经常住在一起</div><h1>生活开始有了“谁来做”的问题。</h1><p class="body">这一周，采购、收拾、洗衣和各种零碎安排明显堆在了一起。你第一次很具体地感到：谈恋爱和一起过日子不是一回事。</p><div class="dialogue">“我们是不是该把这些事说清楚一点？”</div><div class="choices"><button class="choice co" data-a="ACCEPT_SPLIT">“先这样吧，谁有空谁做。”</button><button class="choice co" data-a="NEGOTIATE_SPLIT">“我们按各自时间和擅长的重新分。”</button><button class="choice co" data-a="SET_ROTATION">“固定下来吧，不然最后总有人记着所有事。”</button><button class="choice co" data-a="WITHDRAW">“我现在不想谈，我先自己处理。”</button></div></div></div>`);document.querySelectorAll('.co').forEach(b=>b.onclick=()=>{const r=resolveCohabitation(c,b.dataset.a),negative=r.tags.includes('UNFAIR')||r.tags.includes('UNRESPONSIVE');hiddenRecord({eventId:'COHABITATION',action:b.dataset.a,tags:r.tags,tolerance:negative?'CHANGE_REQUIRED':'ACCEPT',reasonCode:r.tags.includes('UNFAIR')?'UNFAIR_LOAD':null,responseCode:r.code,memoryTitle:'你们开始真正一起过日子',memoryDetail:'家务、计划和责任第一次变成了关系的一部分。'});state.majorStep=0;navigate('career');});}
